name: CI with CD
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: pip install -r requirements.txt
      - uses: actions/setup-node@v5
        with:
          node-version: '23'
      - run: npm install
      - run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'ustc-compiler/2025fall'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
            enable-cache: true
      - name: Install Dependencies
        run: uv sync --locked
      - name: deploy
        if: always()
        run: mkdocs gh-deploy --force
